import sys
from PyQt5 import QtCore, QtGui, QtWidgets  
from PyQt5.QtWidgets import QLabel, QLineEdit, QMessageBox, QComboBox, QPushButton, QTableWidgetItem, QFileDialog, QAction, QMdiArea, QMdiSubWindow
from app_modules import *


class Ui_Aggregalas(object):
    def setupUi(x, Ui_Aggregalas):
        Ui_Aggregalas.setObjectName("Ui_Aggregalas")
        Ui_Aggregalas.resize(580, 605)
        x.centralwidget = QtWidgets.QWidget(Ui_Aggregalas)
        x.centralwidget.setObjectName("centralwidget")
        x.groupBox = QtWidgets.QGroupBox(x.centralwidget)
        x.groupBox.setGeometry(QtCore.QRect(20, 20, 531, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.groupBox.setFont(font)
        x.groupBox.setObjectName("groupBox")
        x.comboBox_Muveletek = QtWidgets.QComboBox(x.groupBox)
        x.comboBox_Muveletek.setGeometry(QtCore.QRect(210, 160, 151, 21))
        x.comboBox_Muveletek.setObjectName("comboBox_Muveletek")
        x.comboBox_Muveletek.addItem("")
        x.comboBox_Muveletek.addItem("")
        x.comboBox_Muveletek.addItem("")
        x.comboBox_Muveletek.addItem("")
        x.comboBox_Muveletek.addItem("")
        x.label = QtWidgets.QLabel(x.groupBox)
        x.label.setGeometry(QtCore.QRect(40, 80, 151, 21))
        x.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label.setWordWrap(True)
        x.label.setObjectName("label")
        x.label_2 = QtWidgets.QLabel(x.groupBox)
        x.label_2.setGeometry(QtCore.QRect(40, 40, 151, 21))
        x.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_2.setWordWrap(True)
        x.label_2.setObjectName("label_2")
        x.label_3 = QtWidgets.QLabel(x.groupBox)
        x.label_3.setGeometry(QtCore.QRect(40, 160, 151, 21))
        x.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_3.setWordWrap(True)
        x.label_3.setObjectName("label_3")
        x.comboBox_forras = QtWidgets.QComboBox(x.groupBox)
        x.comboBox_forras.setGeometry(QtCore.QRect(210, 40, 151, 22))
        x.comboBox_forras.setObjectName("comboBox_forras")
        x.comboBox_forras.addItem("")
        x.comboBox_forras.addItem("")
        x.comboBox_forras.addItem("")
        x.lineEdit_ujAll = QtWidgets.QLineEdit(x.groupBox)
        x.lineEdit_ujAll.setGeometry(QtCore.QRect(210, 80, 151, 20))
        x.lineEdit_ujAll.setObjectName("lineEdit_ujAll")
        x.lineEdit_ujrekord = QtWidgets.QLineEdit(x.groupBox)
        x.lineEdit_ujrekord.setGeometry(QtCore.QRect(210, 120, 151, 20))
        x.lineEdit_ujrekord.setObjectName("lineEdit_ujrekord")
        x.label_4 = QtWidgets.QLabel(x.groupBox)
        x.label_4.setGeometry(QtCore.QRect(40, 120, 151, 21))
        x.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_4.setWordWrap(True)
        x.label_4.setObjectName("label_4")
        x.tableWidget_valtozo = QtWidgets.QTableWidget(x.centralwidget)
        x.tableWidget_valtozo.setGeometry(QtCore.QRect(20, 260, 311, 241))
        x.tableWidget_valtozo.setObjectName("tableWidget_valtozo")
        x.tableWidget_valtozo.setColumnCount(0)
        x.tableWidget_valtozo.setRowCount(0)
        x.listView_szempontok = QtWidgets.QListView(x.centralwidget)
        x.listView_szempontok.setGeometry(QtCore.QRect(370, 260, 181, 241))
        x.listView_szempontok.setObjectName("listView_szempontok")
        x.pushButton_tovabb = QtWidgets.QPushButton(x.centralwidget)
        x.pushButton_tovabb.setGeometry(QtCore.QRect(340, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.pushButton_tovabb.setFont(font)
        x.pushButton_tovabb.setObjectName("pushButton_tovabb")
        x.pushButton_megse = QtWidgets.QPushButton(x.centralwidget)
        x.pushButton_megse.setGeometry(QtCore.QRect(460, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.pushButton_megse.setFont(font)
        x.pushButton_megse.setDefault(True)
        x.pushButton_megse.clicked.connect(lambda: Ui_Aggregalas.close())
        x.pushButton_megse.setObjectName("pushButton_megse")
        x.label_8 = QtWidgets.QLabel(x.centralwidget)
        x.label_8.setGeometry(QtCore.QRect(370, 230, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.label_8.setFont(font)
        x.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        x.label_8.setWordWrap(True)
        x.label_8.setObjectName("label_8")
        x.label_7 = QtWidgets.QLabel(x.centralwidget)
        x.label_7.setGeometry(QtCore.QRect(20, 230, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.label_7.setFont(font)
        x.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        x.label_7.setWordWrap(True)
        x.label_7.setObjectName("label_7")
        Ui_Aggregalas.setCentralWidget(x.centralwidget)
        x.menubar = QtWidgets.QMenuBar(Ui_Aggregalas)
        x.menubar.setGeometry(QtCore.QRect(0, 0, 563, 21))
        x.menubar.setObjectName("menubar")
        Ui_Aggregalas.setMenuBar(x.menubar)
        x.statusbar = QtWidgets.QStatusBar(Ui_Aggregalas)
        x.statusbar.setObjectName("statusbar")
        Ui_Aggregalas.setStatusBar(x.statusbar)

        x.retranslateUi(Ui_Aggregalas)
        QtCore.QMetaObject.connectSlotsByName(Ui_Aggregalas)

    def retranslateUi(x, Ui_Aggregalas):
        _translate = QtCore.QCoreApplication.translate
        Ui_Aggregalas.setWindowTitle(_translate("Ui_Aggregalas", "Aggregálás"))
        x.groupBox.setTitle(_translate("Ui_Aggregalas", "Paraméterek"))
        x.comboBox_Muveletek.setItemText(0, _translate("Ui_Aggregalas", "Összeg"))
        x.comboBox_Muveletek.setItemText(1, _translate("Ui_Aggregalas", "Átlag"))
        x.comboBox_Muveletek.setItemText(2, _translate("Ui_Aggregalas", "Minimum (MIN)"))
        x.comboBox_Muveletek.setItemText(3, _translate("Ui_Aggregalas", "Maximum (MAX)"))
        x.comboBox_Muveletek.setItemText(4, _translate("Ui_Aggregalas", "Elemszám"))
        x.label.setText(_translate("Ui_Aggregalas", "Új adatállomány neve:"))
        x.label_2.setText(_translate("Ui_Aggregalas", "Forrás állomány:"))
        x.label_3.setText(_translate("Ui_Aggregalas", "Aggregálási művelet."))
        x.comboBox_forras.setItemText(0, _translate("Ui_Aggregalas", "Személyek leltára"))
        x.comboBox_forras.setItemText(1, _translate("Ui_Aggregalas", "Települések"))
        x.comboBox_forras.setItemText(2, _translate("Ui_Aggregalas", "Bevételek"))
        x.label_4.setText(_translate("Ui_Aggregalas", "Új rekord neve:"))
        x.pushButton_tovabb.setText(_translate("Ui_Aggregalas", "Tovább"))
        x.pushButton_megse.setText(_translate("Ui_Aggregalas", "Mégse"))
        x.label_8.setText(_translate("Ui_Aggregalas", "Aggregálandó szempontok:"))
        x.label_7.setText(_translate("Ui_Aggregalas", "Aggregálandó változó:"))
