import sys
from PyQt5 import QtCore, QtGui, QtWidgets  
from PyQt5.QtWidgets import QLabel, QLineEdit, QMessageBox, QComboBox, QPushButton, QTableWidgetItem, QFileDialog, QAction, QMdiArea, QMdiSubWindow
from app_modules import *

class Ui_Mintavetel(object):
    def setupUi(x, Ui_Mintavetel):
        Ui_Mintavetel.setObjectName("Ui_Mintavetel")
        Ui_Mintavetel.resize(513, 334)
        x.centralwidget = QtWidgets.QWidget(Ui_Mintavetel)
        x.centralwidget.setObjectName("centralwidget")
        x.groupBox = QtWidgets.QGroupBox(x.centralwidget)
        x.groupBox.setGeometry(QtCore.QRect(20, 20, 471, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.groupBox.setFont(font)
        x.groupBox.setObjectName("groupBox")
        x.comboBox_mintavetel = QtWidgets.QComboBox(x.groupBox)
        x.comboBox_mintavetel.setGeometry(QtCore.QRect(200, 110, 221, 21))
        x.comboBox_mintavetel.setObjectName("comboBox_mintavetel")
        x.comboBox_mintavetel.addItem("")
        x.comboBox_mintavetel.addItem("")
        x.comboBox_mintavetel.addItem("")
        x.comboBox_mintavetel.addItem("")
        x.comboBox_mintavetel.addItem("")
        x.comboBox_mintavetel.addItem("")
        x.comboBox_mintavetel.addItem("")
        x.comboBox_mintavetel.addItem("")
        x.comboBox_mintavetel.addItem("")
        x.comboBox_mintavetel.addItem("")
        x.label = QtWidgets.QLabel(x.groupBox)
        x.label.setGeometry(QtCore.QRect(30, 30, 151, 21))
        x.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label.setWordWrap(True)
        x.label.setObjectName("label")
        x.label_2 = QtWidgets.QLabel(x.groupBox)
        x.label_2.setGeometry(QtCore.QRect(30, 70, 151, 21))
        x.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_2.setWordWrap(True)
        x.label_2.setObjectName("label_2")
        x.label_3 = QtWidgets.QLabel(x.groupBox)
        x.label_3.setGeometry(QtCore.QRect(30, 110, 151, 21))
        x.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_3.setWordWrap(True)
        x.label_3.setObjectName("label_3")
        x.comboBox_forras = QtWidgets.QComboBox(x.groupBox)
        x.comboBox_forras.setGeometry(QtCore.QRect(200, 70, 151, 22))
        x.comboBox_forras.setObjectName("comboBox_forras")
        x.comboBox_forras.addItem("")
        x.comboBox_forras.addItem("")
        x.comboBox_forras.addItem("")
        x.lineEdit_ujallomany = QtWidgets.QLineEdit(x.groupBox)
        x.lineEdit_ujallomany.setGeometry(QtCore.QRect(200, 30, 151, 20))
        x.lineEdit_ujallomany.setObjectName("lineEdit_ujallomany")
        x.label_4 = QtWidgets.QLabel(x.groupBox)
        x.label_4.setGeometry(QtCore.QRect(30, 150, 151, 21))
        x.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_4.setWordWrap(True)
        x.label_4.setObjectName("label_4")
        x.spinBox = QtWidgets.QSpinBox(x.groupBox)
        x.spinBox.setGeometry(QtCore.QRect(200, 150, 111, 22))
        x.spinBox.setMaximum(1000000000)
        x.spinBox.setObjectName("spinBox")
        x.pushButton_futtat = QtWidgets.QPushButton(x.centralwidget)
        x.pushButton_futtat.setGeometry(QtCore.QRect(280, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.pushButton_futtat.setFont(font)
        x.pushButton_futtat.setObjectName("pushButton_futtat")
        x.pushButton_megse = QtWidgets.QPushButton(x.centralwidget)
        x.pushButton_megse.setGeometry(QtCore.QRect(400, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.pushButton_megse.setFont(font)
        x.pushButton_megse.setDefault(True)
        x.pushButton_megse.clicked.connect(lambda: Ui_Mintavetel.close())
        x.pushButton_megse.setObjectName("pushButton_megse")
        Ui_Mintavetel.setCentralWidget(x.centralwidget)
        x.menubar = QtWidgets.QMenuBar(Ui_Mintavetel)
        x.menubar.setGeometry(QtCore.QRect(0, 0, 513, 21))
        x.menubar.setObjectName("menubar")
        Ui_Mintavetel.setMenuBar(x.menubar)
        x.statusbar = QtWidgets.QStatusBar(Ui_Mintavetel)
        x.statusbar.setObjectName("statusbar")
        Ui_Mintavetel.setStatusBar(x.statusbar)

        x.retranslateUi(Ui_Mintavetel)
        QtCore.QMetaObject.connectSlotsByName(Ui_Mintavetel)

    def retranslateUi(x, Ui_Mintavetel):
        _translate = QtCore.QCoreApplication.translate
        Ui_Mintavetel.setWindowTitle(_translate("Ui_Mintavetel", "Minta létrehozása"))
        x.groupBox.setTitle(_translate("Ui_Mintavetel", "Paraméterek"))
        x.comboBox_mintavetel.setItemText(0, _translate("Ui_Mintavetel", "Független, azonos elosztású"))
        x.comboBox_mintavetel.setItemText(1, _translate("Ui_Mintavetel", "Egyszerű véletlen"))
        x.comboBox_mintavetel.setItemText(2, _translate("Ui_Mintavetel", "Szisztematikus"))
        x.comboBox_mintavetel.setItemText(3, _translate("Ui_Mintavetel", "Rétegzett"))
        x.comboBox_mintavetel.setItemText(4, _translate("Ui_Mintavetel", "Többlépcsős"))
        x.comboBox_mintavetel.setItemText(5, _translate("Ui_Mintavetel", "Csoportos"))
        x.comboBox_mintavetel.setItemText(6, _translate("Ui_Mintavetel", "Szisztematikus"))
        x.comboBox_mintavetel.setItemText(7, _translate("Ui_Mintavetel", "Kvóta szerinti"))
        x.comboBox_mintavetel.setItemText(8, _translate("Ui_Mintavetel", "Koncentrált"))
        x.comboBox_mintavetel.setItemText(9, _translate("Ui_Mintavetel", "Önkényes"))
        x.label.setText(_translate("Ui_Mintavetel", "Új adatállomány neve:"))
        x.label_2.setText(_translate("Ui_Mintavetel", "Forrás állomány:"))
        x.label_3.setText(_translate("Ui_Mintavetel", "Mintavételi eljárás:"))
        x.comboBox_forras.setItemText(0, _translate("Ui_Mintavetel", "Személyek leltára"))
        x.comboBox_forras.setItemText(1, _translate("Ui_Mintavetel", "Települések"))
        x.comboBox_forras.setItemText(2, _translate("Ui_Mintavetel", "Bevételek"))
        x.label_4.setText(_translate("Ui_Mintavetel", "Minta mérete:"))
        x.pushButton_futtat.setText(_translate("Ui_Mintavetel", "Futtatás"))
        x.pushButton_megse.setText(_translate("Ui_Mintavetel", "Mégse"))
