import sys
from PyQt5 import QtCore, QtGui, QtWidgets  
from PyQt5.QtWidgets import QLabel, QLineEdit, QMessageBox, QComboBox, QPushButton, QTableWidgetItem, QFileDialog, QAction, QMdiArea, QMdiSubWindow
from app_modules import *


class Ui_Parositas(object):
    def setupUi(x, Ui_Parositas):
        Ui_Parositas.setObjectName("Ui_Parositas")
        Ui_Parositas.resize(591, 681)
        x.centralwidget = QtWidgets.QWidget(Ui_Parositas)
        x.centralwidget.setObjectName("centralwidget")
        x.groupBox = QtWidgets.QGroupBox(x.centralwidget)
        x.groupBox.setGeometry(QtCore.QRect(30, 10, 531, 261))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.groupBox.setFont(font)
        x.groupBox.setObjectName("groupBox")
        x.lineEdit_ujallomany = QtWidgets.QLineEdit(x.groupBox)
        x.lineEdit_ujallomany.setGeometry(QtCore.QRect(210, 40, 151, 20))
        x.lineEdit_ujallomany.setObjectName("lineEdit_ujallomany")
        x.comboBox_elsodlegesAll = QtWidgets.QComboBox(x.groupBox)
        x.comboBox_elsodlegesAll.setGeometry(QtCore.QRect(210, 80, 151, 22))
        x.comboBox_elsodlegesAll.setObjectName("comboBox_elsodlegesAll")
        x.comboBox_elsodlegesAll.addItem("")
        x.comboBox_elsodlegesAll.addItem("")
        x.comboBox_elsodlegesAll.addItem("")
        x.comboBox_masodlagosAll = QtWidgets.QComboBox(x.groupBox)
        x.comboBox_masodlagosAll.setGeometry(QtCore.QRect(210, 120, 151, 22))
        x.comboBox_masodlagosAll.setObjectName("comboBox_masodlagosAll")
        x.comboBox_masodlagosAll.addItem("")
        x.comboBox_masodlagosAll.addItem("")
        x.comboBox_kulcs = QtWidgets.QComboBox(x.groupBox)
        x.comboBox_kulcs.setGeometry(QtCore.QRect(210, 160, 151, 22))
        x.comboBox_kulcs.setObjectName("comboBox_kulcs")
        x.checkBox = QtWidgets.QCheckBox(x.groupBox)
        x.checkBox.setGeometry(QtCore.QRect(210, 209, 91, 17))
        x.checkBox.setObjectName("checkBox")
        x.checkBox_2 = QtWidgets.QCheckBox(x.groupBox)
        x.checkBox_2.setGeometry(QtCore.QRect(210, 229, 111, 16))
        x.checkBox_2.setObjectName("checkBox_2")
        x.checkBox_3 = QtWidgets.QCheckBox(x.groupBox)
        x.checkBox_3.setGeometry(QtCore.QRect(330, 210, 101, 16))
        x.checkBox_3.setObjectName("checkBox_3")
        x.checkBox_4 = QtWidgets.QCheckBox(x.groupBox)
        x.checkBox_4.setGeometry(QtCore.QRect(330, 229, 151, 16))
        x.checkBox_4.setObjectName("checkBox_4")
        x.label = QtWidgets.QLabel(x.groupBox)
        x.label.setGeometry(QtCore.QRect(40, 40, 151, 21))
        x.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label.setWordWrap(True)
        x.label.setObjectName("label")
        x.label_2 = QtWidgets.QLabel(x.groupBox)
        x.label_2.setGeometry(QtCore.QRect(40, 80, 151, 21))
        x.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_2.setWordWrap(True)
        x.label_2.setObjectName("label_2")
        x.label_3 = QtWidgets.QLabel(x.groupBox)
        x.label_3.setGeometry(QtCore.QRect(40, 120, 151, 21))
        x.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_3.setWordWrap(True)
        x.label_3.setObjectName("label_3")
        x.label_4 = QtWidgets.QLabel(x.groupBox)
        x.label_4.setGeometry(QtCore.QRect(40, 160, 151, 21))
        x.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_4.setWordWrap(True)
        x.label_4.setObjectName("label_4")
        x.label_5 = QtWidgets.QLabel(x.groupBox)
        x.label_5.setGeometry(QtCore.QRect(70, 210, 121, 16))
        x.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_5.setWordWrap(True)
        x.label_5.setObjectName("label_5")
        x.listWidget_elsodleges = QtWidgets.QListWidget(x.centralwidget)
        x.listWidget_elsodleges.setGeometry(QtCore.QRect(30, 350, 121, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.listWidget_elsodleges.setFont(font)
        x.listWidget_elsodleges.setAutoFillBackground(True)
        x.listWidget_elsodleges.setFrameShape(QtWidgets.QFrame.StyledPanel)
        x.listWidget_elsodleges.setFrameShadow(QtWidgets.QFrame.Sunken)
        x.listWidget_elsodleges.setLineWidth(1)
        x.listWidget_elsodleges.setMidLineWidth(0)
        x.listWidget_elsodleges.setProperty("showDropIndicator", False)
        x.listWidget_elsodleges.setDragEnabled(False)
        x.listWidget_elsodleges.setDragDropOverwriteMode(False)
        x.listWidget_elsodleges.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        x.listWidget_elsodleges.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        x.listWidget_elsodleges.setAlternatingRowColors(True)
        x.listWidget_elsodleges.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        x.listWidget_elsodleges.setResizeMode(QtWidgets.QListView.Fixed)
        x.listWidget_elsodleges.setLayoutMode(QtWidgets.QListView.SinglePass)
        x.listWidget_elsodleges.setViewMode(QtWidgets.QListView.ListMode)
        x.listWidget_elsodleges.setUniformItemSizes(False)
        x.listWidget_elsodleges.setSelectionRectVisible(False)
        x.listWidget_elsodleges.setObjectName("listWidget_elsodleges")
        item = QtWidgets.QListWidgetItem()
        x.listWidget_elsodleges.addItem(item)
        item = QtWidgets.QListWidgetItem()
        x.listWidget_elsodleges.addItem(item)
        item = QtWidgets.QListWidgetItem()
        x.listWidget_elsodleges.addItem(item)
        item = QtWidgets.QListWidgetItem()
        x.listWidget_elsodleges.addItem(item)
        x.pushButton_futtat = QtWidgets.QPushButton(x.centralwidget)
        x.pushButton_futtat.setGeometry(QtCore.QRect(350, 590, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.pushButton_futtat.setFont(font)
        x.pushButton_futtat.setObjectName("pushButton_futtat")
        x.pushButton_megse = QtWidgets.QPushButton(x.centralwidget)
        x.pushButton_megse.setGeometry(QtCore.QRect(470, 590, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.pushButton_megse.setFont(font)
        x.pushButton_megse.setDefault(True)
        x.pushButton_megse.clicked.connect(lambda: Ui_Parositas.close())
        x.pushButton_megse.setObjectName("pushButton_megse")
        x.label_6 = QtWidgets.QLabel(x.centralwidget)
        x.label_6.setGeometry(QtCore.QRect(30, 280, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        x.label_6.setFont(font)
        x.label_6.setObjectName("label_6")
        x.label_7 = QtWidgets.QLabel(x.centralwidget)
        x.label_7.setGeometry(QtCore.QRect(30, 320, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.label_7.setFont(font)
        x.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        x.label_7.setWordWrap(True)
        x.label_7.setObjectName("label_7")
        x.label_8 = QtWidgets.QLabel(x.centralwidget)
        x.label_8.setGeometry(QtCore.QRect(320, 320, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.label_8.setFont(font)
        x.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        x.label_8.setWordWrap(True)
        x.label_8.setObjectName("label_8")
        x.listWidget_elsodleges_2 = QtWidgets.QListWidget(x.centralwidget)
        x.listWidget_elsodleges_2.setGeometry(QtCore.QRect(320, 350, 121, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.listWidget_elsodleges_2.setFont(font)
        x.listWidget_elsodleges_2.setAutoFillBackground(True)
        x.listWidget_elsodleges_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        x.listWidget_elsodleges_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        x.listWidget_elsodleges_2.setLineWidth(1)
        x.listWidget_elsodleges_2.setMidLineWidth(0)
        x.listWidget_elsodleges_2.setProperty("showDropIndicator", False)
        x.listWidget_elsodleges_2.setDragEnabled(False)
        x.listWidget_elsodleges_2.setDragDropOverwriteMode(False)
        x.listWidget_elsodleges_2.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        x.listWidget_elsodleges_2.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        x.listWidget_elsodleges_2.setAlternatingRowColors(True)
        x.listWidget_elsodleges_2.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        x.listWidget_elsodleges_2.setResizeMode(QtWidgets.QListView.Fixed)
        x.listWidget_elsodleges_2.setLayoutMode(QtWidgets.QListView.SinglePass)
        x.listWidget_elsodleges_2.setViewMode(QtWidgets.QListView.ListMode)
        x.listWidget_elsodleges_2.setUniformItemSizes(False)
        x.listWidget_elsodleges_2.setSelectionRectVisible(False)
        x.listWidget_elsodleges_2.setObjectName("listWidget_elsodleges_2")
        item = QtWidgets.QListWidgetItem()
        x.listWidget_elsodleges_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        x.listWidget_elsodleges_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        x.listWidget_elsodleges_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        x.listWidget_elsodleges_2.addItem(item)
        Ui_Parositas.setCentralWidget(x.centralwidget)
        x.menubar = QtWidgets.QMenuBar(Ui_Parositas)
        x.menubar.setGeometry(QtCore.QRect(0, 0, 591, 21))
        x.menubar.setObjectName("menubar")
        Ui_Parositas.setMenuBar(x.menubar)
        x.statusbar = QtWidgets.QStatusBar(Ui_Parositas)
        x.statusbar.setObjectName("statusbar")
        Ui_Parositas.setStatusBar(x.statusbar)

        x.retranslateUi(Ui_Parositas)
        QtCore.QMetaObject.connectSlotsByName(Ui_Parositas)

    def retranslateUi(x, Ui_Parositas):
        _translate = QtCore.QCoreApplication.translate
        Ui_Parositas.setWindowTitle(_translate("Ui_Parositas", "Párosítás"))
        x.groupBox.setTitle(_translate("Ui_Parositas", "Paraméterek"))
        x.comboBox_elsodlegesAll.setItemText(0, _translate("Ui_Parositas", "Személyek leltára"))
        x.comboBox_elsodlegesAll.setItemText(1, _translate("Ui_Parositas", "Települések"))
        x.comboBox_elsodlegesAll.setItemText(2, _translate("Ui_Parositas", "Bevételek"))
        x.comboBox_masodlagosAll.setItemText(0, _translate("Ui_Parositas", "Települések"))
        x.comboBox_masodlagosAll.setItemText(1, _translate("Ui_Parositas", "Bevételek"))
        x.checkBox.setText(_translate("Ui_Parositas", "LEFT JOIN"))
        x.checkBox_2.setText(_translate("Ui_Parositas", "RIGHT JOIN"))
        x.checkBox_3.setText(_translate("Ui_Parositas", "INNER JOIN"))
        x.checkBox_4.setText(_translate("Ui_Parositas", "FULL OUTER JOIN"))
        x.label.setText(_translate("Ui_Parositas", "Új állomány neve:"))
        x.label_2.setText(_translate("Ui_Parositas", "Elsődleges állomány:"))
        x.label_3.setText(_translate("Ui_Parositas", "Másodlagos állomány:"))
        x.label_4.setText(_translate("Ui_Parositas", "Közös kulcs:"))
        x.label_5.setText(_translate("Ui_Parositas", "SQL JOINS:"))
        __sortingEnabled = x.listWidget_elsodleges.isSortingEnabled()
        x.listWidget_elsodleges.setSortingEnabled(False)
        item = x.listWidget_elsodleges.item(0)
        item.setText(_translate("Ui_Parositas", "testsuly"))
        item = x.listWidget_elsodleges.item(1)
        item.setText(_translate("Ui_Parositas", "datum"))
        item = x.listWidget_elsodleges.item(2)
        item.setText(_translate("Ui_Parositas", "phone"))
        item = x.listWidget_elsodleges.item(3)
        item.setText(_translate("Ui_Parositas", "address"))
        x.listWidget_elsodleges.setSortingEnabled(__sortingEnabled)
        x.pushButton_futtat.setText(_translate("Ui_Parositas", "Futtatás"))
        x.pushButton_megse.setText(_translate("Ui_Parositas", "Mégse"))
        x.label_6.setText(_translate("Ui_Parositas", "Az új állomány szerkezetének megadása:"))
        x.label_7.setText(_translate("Ui_Parositas", "Elsődleges állományból:"))
        x.label_8.setText(_translate("Ui_Parositas", "Másodlagos állományból:"))
        __sortingEnabled = x.listWidget_elsodleges_2.isSortingEnabled()
        x.listWidget_elsodleges_2.setSortingEnabled(False)
        item = x.listWidget_elsodleges_2.item(0)
        item.setText(_translate("Ui_Parositas", "telepules_id"))
        item = x.listWidget_elsodleges_2.item(1)
        item.setText(_translate("Ui_Parositas", "postcode"))
        item = x.listWidget_elsodleges_2.item(2)
        item.setText(_translate("Ui_Parositas", "address"))
        item = x.listWidget_elsodleges_2.item(3)
        item.setText(_translate("Ui_Parositas", "datum"))
        x.listWidget_elsodleges_2.setSortingEnabled(__sortingEnabled)
