import sys
from PyQt5 import QtCore, QtGui, QtWidgets  
from PyQt5.QtWidgets import QLabel, QLineEdit, QMessageBox, QComboBox, QPushButton, QTableWidgetItem, QFileDialog, QAction, QMdiArea, QMdiSubWindow
from app_modules import *

class Ui_Rekordleirasok(QtWidgets.QMainWindow):
    def setupUi(x,  Ui_Rekordleirasok):
         Ui_Rekordleirasok.setObjectName("Ui_Rekordleirasok")
         Ui_Rekordleirasok.resize(800, 500)
         
         Ui_Rekordleirasok.setWindowTitle("Rekordleírások kezelése")        
         
         x.tableWidget = QtWidgets.QTableWidget(Ui_Rekordleirasok)        
         x.tableWidget.setGeometry(QtCore.QRect(60, 75, 650, 370))
         x.tableWidget.setObjectName("tableWidget")
         x.tableWidget.horizontalHeader().setStretchLastSection(True)
         
         x.tableWidget.setColumnCount(6)
         x.tableWidget.setRowCount(3)
         
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setVerticalHeaderItem(0, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setVerticalHeaderItem(1, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setVerticalHeaderItem(2, item)
         
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setHorizontalHeaderItem(0, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setHorizontalHeaderItem(1, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setHorizontalHeaderItem(2, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setHorizontalHeaderItem(3, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setHorizontalHeaderItem(4, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setHorizontalHeaderItem(5, item)
         
         
         
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(0, 0, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(0, 1, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(0, 2, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(0, 4, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(0, 5, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(1, 0, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(1, 1, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(1, 2, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(1, 4, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(1, 5, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(2, 0, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(2, 1, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(2, 2, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(2, 4, item)
         item = QtWidgets.QTableWidgetItem()
         x.tableWidget.setItem(2, 5, item)
              
         #x.pushButton_modosit = QtWidgets.QPushButton(Ui_Rekordleirasok)
       #  x.pushButton_modosit.setGeometry(QtCore.QRect(60, 26, 91, 23))
        # x.pushButton_modosit.setObjectName("pushButton_modosit")          
         x.pushButton_ujrekord = QtWidgets.QPushButton(Ui_Rekordleirasok)
         x.pushButton_ujrekord.setGeometry(QtCore.QRect(60, 26, 140, 23))
         x.pushButton_ujrekord.setObjectName("pushButton_ujrekord")    
         x.pushButton_mezok = QtWidgets.QPushButton(Ui_Rekordleirasok)
         x.pushButton_mezok.setGeometry(QtCore.QRect(240, 26, 91, 23))
         x.pushButton_mezok.setObjectName("pushButton_mezok")               
         121
         x.pushButton_torol = QtWidgets.QPushButton(Ui_Rekordleirasok)
         x.pushButton_torol.setGeometry(QtCore.QRect(371, 26, 91, 23))
         x.pushButton_torol.setObjectName("pushButton_torol") 


         x.valtoztatUi(Ui_Rekordleirasok)
         QtCore.QMetaObject.connectSlotsByName(Ui_Rekordleirasok)
         
          
         x.pushButton_mezok.clicked.connect(x.rekord_mezok_window)
         
         x.pushButton_ujrekord.clicked.connect(x.rekord_uj_Window)
         
         #ez fogja törölni a kiválasztott sort 
         x.pushButton_torol.clicked.connect(x.deleteCurrentRow)
          #modosit torol gomb allapot valtozasahoz 
         x.tableWidget.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)
         x.tableWidget.selectionModel().selectionChanged.connect(
             x.on_selection_changed
         )
 
         x.on_selection_changed()

    def deleteCurrentRow(self):
        result = QtWidgets.QMessageBox.question(self,
                      "Törlés megerősítése...",
                      "Biztos ki akarod törölni a kiválaszott sorokat?",
                      QtWidgets.QMessageBox.Yes| QtWidgets.QMessageBox.No)
        

        if result == QtWidgets.QMessageBox.Yes:
            indexes = self.tableWidget.selectionModel().selectedRows() 
            for index in sorted(indexes):
                self.tableWidget.removeRow(index.row())                
        
    def on_selection_changed(self):
        #self.pushButton_modosit.setEnabled(
        #    bool(self.tableWidget.selectionModel().selectedRows())
       #)
        self.pushButton_torol.setEnabled(
            bool(self.tableWidget.selectionModel().selectedRows())
       )
        self.pushButton_mezok.setEnabled(
            bool(self.tableWidget.selectionModel().selectedRows())
       )
        self.pushButton_ujrekord.setEnabled(
            bool(self.tableWidget.selectionModel().selectedRows())
       )

    def valtoztatUi(x, Ui_Rekordleirasok):
         _translate = QtCore.QCoreApplication.translate
         Ui_Rekordleirasok.setWindowTitle(_translate("Ui_Rekordleirasok", "Rekordleírások kezelése"))
         item = x.tableWidget.verticalHeaderItem(0)
         item.setText(_translate("Ui_Rekordleirasok", "1"))
         item = x.tableWidget.verticalHeaderItem(1)
         item.setText(_translate("Ui_Rekordleirasok", "2"))
         item = x.tableWidget.verticalHeaderItem(2)
         item.setText(_translate("Ui_Rekordleirasok", "3"))
         
         
         item = x.tableWidget.horizontalHeaderItem(0)
         item.setText(_translate("Ui_Rekordleirasok", "Rekord neve"))
         item = x.tableWidget.horizontalHeaderItem(1)
         item.setText(_translate("Ui_Rekordleirasok", "Típus"))
         item = x.tableWidget.horizontalHeaderItem(2)
         item.setText(_translate("Ui_Rekordleirasok", "Címke"))
         item = x.tableWidget.horizontalHeaderItem(3)
         item.setText(_translate("Ui_Rekordleirasok", "Leírás"))
         item = x.tableWidget.horizontalHeaderItem(4)
         item.setText(_translate("Ui_Rekordleirasok", "Utolsó módosítás"))
         item = x.tableWidget.horizontalHeaderItem(5)
         item.setText(_translate("Ui_Rekordleirasok", "Létrehozva"))
         
         
         __sortingEnabled = x.tableWidget.isSortingEnabled()
         x.tableWidget.setSortingEnabled(False)
         item = x.tableWidget.item(0, 0)
         item.setText(_translate("Ui_Rekordleirasok", "szemelyek"))
         item = x.tableWidget.item(0, 1)
         item.setText(_translate("Ui_Rekordleirasok", "SAS"))
         item = x.tableWidget.item(0, 2)
         item.setText(_translate("Ui_Rekordleirasok", "Személyek"))
         item = x.tableWidget.item(0, 4)
         item.setText(_translate("Ui_Rekordleirasok", "2020.10.12. 19:20"))
         item = x.tableWidget.item(0, 5)
         item.setText(_translate("Ui_Rekordleirasok", "2020.10.10. 10:20"))
        
         
         item = x.tableWidget.item(1, 0)
         item.setText(_translate("Ui_Rekordleirasok", "telepulesek"))
         item = x.tableWidget.item(1, 1)
         item.setText(_translate("Ui_Rekordleirasok", "SAS"))
         item = x.tableWidget.item(1, 2)
         item.setText(_translate("Ui_Rekordleirasok", "Települések"))
         item = x.tableWidget.item(1, 4)
         item.setText(_translate("Ui_Rekordleirasok", "2020.10.11. 15:45"))
         item = x.tableWidget.item(1, 5)
         item.setText(_translate("Ui_Rekordleirasok", "2020.09.09. 13:55"))
         
         item = x.tableWidget.item(2, 0)
         item.setText(_translate("Ui_Rekordleirasok", "bevetelek"))
         item = x.tableWidget.item(2, 1)
         item.setText(_translate("Ui_Rekordleirasok", "SAS"))
         item = x.tableWidget.item(2, 2)
         item.setText(_translate("Ui_Rekordleirasok", "Bevételek"))
         item = x.tableWidget.item(2, 4)
         item.setText(_translate("Ui_Rekordleirasok", "2020.08.13. 17:13"))
         item = x.tableWidget.item(2, 5)
         item.setText(_translate("Ui_Rekordleirasok", "2020.07.09. 09:09"))

 
         x.tableWidget.setSortingEnabled(__sortingEnabled)
      
         x.pushButton_torol.setText(_translate("Ui_Rekordleirasok", "Törlés"))
         x.pushButton_mezok.setText(_translate("Ui_Rekordleirasok", "Mezők kezelése"))
         x.pushButton_ujrekord.setText(_translate("Ui_Rekordleirasok", "Új rekordleírás létrehozása"))

   
    
    def rekord_mezok_window(x):
         x.window = QtWidgets.QMainWindow()
         x.ui = Ui_Mezok()
         x.ui.setupUi(x.window)
         x.window.show()     
            
    def rekord_uj_Window(x):
        x.window = QtWidgets.QMainWindow()
        x.ui = Ui_Rekord_Uj()
        x.ui.setupUi(x.window)            
        x.window.show()     
      
      
class Ui_Rekord_Uj(object):
    def setupUi(x, Ui_Rekord_Uj):
        Ui_Rekord_Uj.setObjectName("Ui_Rekord_Uj")
        Ui_Rekord_Uj.resize(429, 392)
        x.centralwidget = QtWidgets.QWidget(Ui_Rekord_Uj)
        x.centralwidget.setObjectName("centralwidget")
        x.tabWidget = QtWidgets.QTabWidget(x.centralwidget)
        x.tabWidget.setGeometry(QtCore.QRect(10, 10, 391, 281))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.tabWidget.setFont(font)
        x.tabWidget.setObjectName("tabWidget")
        x.tab_attributum = QtWidgets.QWidget()
        x.tab_attributum.setObjectName("tab_attributum")
        x.comboBox_tipus = QtWidgets.QComboBox(x.tab_attributum)
        x.comboBox_tipus.setGeometry(QtCore.QRect(150, 150, 111, 22))
        x.comboBox_tipus.setObjectName("comboBox_tipus")
        x.comboBox_tipus.addItem("")
        x.comboBox_tipus.addItem("")
        x.lineEdit_rekordnev = QtWidgets.QLineEdit(x.tab_attributum)
        x.lineEdit_rekordnev.setGeometry(QtCore.QRect(150, 30, 171, 20))
        x.lineEdit_rekordnev.setObjectName("lineEdit_rekordnev")
        x.label = QtWidgets.QLabel(x.tab_attributum)
        x.label.setGeometry(QtCore.QRect(30, 30, 111, 21))
        x.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label.setObjectName("label")
        x.label_2 = QtWidgets.QLabel(x.tab_attributum)
        x.label_2.setGeometry(QtCore.QRect(30, 150, 111, 21))
        x.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_2.setObjectName("label_2")
        x.lineEdit_cimke = QtWidgets.QLineEdit(x.tab_attributum)
        x.lineEdit_cimke.setGeometry(QtCore.QRect(150, 70, 171, 20))
        x.lineEdit_cimke.setObjectName("lineEdit_cimke")
        x.label_3 = QtWidgets.QLabel(x.tab_attributum)
        x.label_3.setGeometry(QtCore.QRect(10, 70, 131, 21))
        x.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_3.setObjectName("label_3")
        x.lineEdit_leiras = QtWidgets.QLineEdit(x.tab_attributum)
        x.lineEdit_leiras.setGeometry(QtCore.QRect(150, 110, 171, 20))
        x.lineEdit_leiras.setObjectName("lineEdit_leiras")
        x.label_4 = QtWidgets.QLabel(x.tab_attributum)
        x.label_4.setGeometry(QtCore.QRect(10, 110, 131, 21))
        x.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        x.label_4.setObjectName("label_4")
        x.tabWidget.addTab(x.tab_attributum, "")
        x.pushButton_Megse = QtWidgets.QPushButton(x.centralwidget)
        x.pushButton_Megse.setGeometry(QtCore.QRect(310, 310, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.pushButton_Megse.setFont(font)
        x.pushButton_Megse.clicked.connect(lambda: Ui_Rekord_Uj.close())
        x.pushButton_Megse.setDefault(True)
        x.pushButton_Megse.setObjectName("pushButton_Megse")
        x.pushButton_Mentes = QtWidgets.QPushButton(x.centralwidget)
        x.pushButton_Mentes.setGeometry(QtCore.QRect(210, 310, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.pushButton_Mentes.setFont(font)
        x.pushButton_Mentes.setObjectName("pushButton_Mentes")
        x.pushButton_Kezeles = QtWidgets.QPushButton(x.centralwidget)
        x.pushButton_Kezeles.setGeometry(QtCore.QRect(70, 310, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.pushButton_Kezeles.setFont(font)
        x.pushButton_Kezeles.setObjectName("pushButton_Kezeles")
        Ui_Rekord_Uj.setCentralWidget(x.centralwidget)
        x.statusbar = QtWidgets.QStatusBar(Ui_Rekord_Uj)
        x.statusbar.setObjectName("statusbar")
        Ui_Rekord_Uj.setStatusBar(x.statusbar)

        x.retranslateUi(Ui_Rekord_Uj)
        x.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Ui_Rekord_Uj)

        x.pushButton_Kezeles.clicked.connect(x.open_Ui_Mezok_Szerk)
        

    def retranslateUi(x, Ui_Rekord_Uj):
        _translate = QtCore.QCoreApplication.translate
        Ui_Rekord_Uj.setWindowTitle(_translate("Ui_Rekord_Uj", "Új rekord létrehozása"))
        x.comboBox_tipus.setItemText(0, _translate("Ui_Rekord_Uj", "SAS"))
        x.comboBox_tipus.setItemText(1, _translate("Ui_Rekord_Uj", "SQL"))
        x.label.setText(_translate("Ui_Rekord_Uj", "Rekord neve:"))
        x.label_2.setText(_translate("Ui_Rekord_Uj", "Típus:"))
        x.label_3.setText(_translate("Ui_Rekord_Uj", "Nyomtatási címke:"))
        x.label_4.setText(_translate("Ui_Rekord_Uj", "Leírása:"))
        x.tabWidget.setTabText(x.tabWidget.indexOf(x.tab_attributum), _translate("Ui_Rekord_Uj", "Attribútumok"))
        x.pushButton_Megse.setText(_translate("Ui_Rekord_Uj", "Mégse"))
        x.pushButton_Mentes.setText(_translate("Ui_Rekord_Uj", "Mentés"))
        x.pushButton_Kezeles.setText(_translate("Ui_Rekord_Uj", "Mezők kezelése"))
        
    def open_Ui_Mezok_Szerk(x):
        x.window = QtWidgets.QMainWindow()
        x.ui = Ui_Mezok_Szerk()
        x.ui.setupUi(x.window)
        x.window.setWindowTitle("Új rekord mezőinek a kiválaszása")
        x.window.show()    
         
        



class Ui_Mezok(object):
    def setupUi(x, Ui_Mezok):
        Ui_Mezok.setObjectName("Ui_Mezok")
        Ui_Mezok.resize(687, 515)
        x.centralwidget = QtWidgets.QWidget(Ui_Mezok)
        x.centralwidget.setObjectName("centralwidget")
        x.frame = QtWidgets.QFrame(x.centralwidget)
        x.frame.setGeometry(QtCore.QRect(10, 0, 671, 471))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.frame.setFont(font)
        x.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        x.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        x.frame.setObjectName("frame")
        x.pushButton_szerk = QtWidgets.QPushButton(x.frame)
        x.pushButton_szerk.setGeometry(QtCore.QRect(30, 20, 260, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        x.pushButton_szerk.setIcon(icon)
        x.pushButton_szerk.setIconSize(QtCore.QSize(20, 20))
        x.pushButton_szerk.setDefault(True)
        x.pushButton_szerk.setObjectName("pushButton_szerk")
      #  x.pushButton_modosit = QtWidgets.QPushButton(x.frame)
      #  x.pushButton_modosit.setGeometry(QtCore.QRect(170, 20, 111, 31))
      #  icon1 = QtGui.QIcon()
      #  icon1.addPixmap(QtGui.QPixmap("edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #x.pushButton_modosit.setIcon(icon1)
        #x.pushButton_modosit.setIconSize(QtCore.QSize(20, 20))
        #x.pushButton_modosit.setObjectName("pushButton_modosit")
        #x.pushButton_metatrendel = QtWidgets.QPushButton(x.frame)
        #x.pushButton_metatrendel.setGeometry(QtCore.QRect(300, 20, 151, 31))
        #x.pushButton_metatrendel.setObjectName("pushButton_metatrendel")
        x.pushButton_torol = QtWidgets.QPushButton(x.frame)
        x.pushButton_torol.setGeometry(QtCore.QRect(320, 20, 131, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        x.pushButton_torol.setIcon(icon2)
        x.pushButton_torol.setIconSize(QtCore.QSize(20, 20))
        x.pushButton_torol.setObjectName("pushButton_torol")
        x.pushButton_frissit = QtWidgets.QPushButton(x.frame)
        x.pushButton_frissit.setGeometry(QtCore.QRect(620, 20, 41, 31))
        x.pushButton_frissit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        x.pushButton_frissit.setIcon(icon3)
        x.pushButton_frissit.setIconSize(QtCore.QSize(30, 30))
        x.pushButton_frissit.setFlat(True)
        x.pushButton_frissit.setObjectName("pushButton_frissit")
        x.tableWidget = QtWidgets.QTableWidget(x.frame)
        x.tableWidget.setGeometry(QtCore.QRect(30, 100, 601, 341))
        x.tableWidget.setShowGrid(True)
        x.tableWidget.setRowCount(10)
        x.tableWidget.setColumnCount(3)
        x.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget.setHorizontalHeaderItem(3, item)
        x.tableWidget.horizontalHeader().setStretchLastSection(True)
        x.tableWidget.verticalHeader().setVisible(True)
        x.tableWidget.verticalHeader().setSortIndicatorShown(False)
        x.tableWidget.verticalHeader().setStretchLastSection(False)
        Ui_Mezok.setCentralWidget(x.centralwidget)
        x.menubar = QtWidgets.QMenuBar(Ui_Mezok)
        x.menubar.setGeometry(QtCore.QRect(0, 0, 687, 21))
        x.menubar.setObjectName("menubar")
        Ui_Mezok.setMenuBar(x.menubar)
        x.statusbar = QtWidgets.QStatusBar(Ui_Mezok)
        x.statusbar.setObjectName("statusbar")
        Ui_Mezok.setStatusBar(x.statusbar)
        
        x.pushButton_szerk.clicked.connect(x.open_Ui_Mezok_Szerk)
        #x.pushButton_modosit.clicked.connect(x.open_Ui_Mezok_Modosit)
        
        x.retranslateUi(Ui_Mezok)
        QtCore.QMetaObject.connectSlotsByName(Ui_Mezok)

    def retranslateUi(x, Ui_Mezok):
        _translate = QtCore.QCoreApplication.translate
        Ui_Mezok.setWindowTitle(_translate("Ui_Mezok", "Mezők"))
        x.pushButton_szerk.setText(_translate("Ui_Mezok", "Rekordhoz tartozó mezők kezelése"))
      #  x.pushButton_modosit.setText(_translate("Ui_Mezok", "Módosít"))
      #  x.pushButton_metatrendel.setText(_translate("Ui_Mezok", "Meta hozzárendelés"))
     #   x.pushButton_torol.setText(_translate("Ui_Mezok", "Törlés"))
        x.tableWidget.setSortingEnabled(True)
        item = x.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Ui_Mezok", "Mező neve"))
        item = x.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Ui_Mezok", "Típus"))
        item = x.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Ui_Mezok", "Hossz"))
        
    
    
    
    def open_Ui_Mezok_Szerk(x):
        x.window = QtWidgets.QMainWindow()
        x.ui = Ui_Mezok_Szerk()
        x.ui.setupUi(x.window)
        x.window.show()    
        

class Ui_Mezok_Szerk(object):
    def setupUi(x, Ui_Mezok_Szerk):
        Ui_Mezok_Szerk.setObjectName("Ui_Mezok_Szerk")
        Ui_Mezok_Szerk.resize(665, 674)
        x.centralwidget = QtWidgets.QWidget(Ui_Mezok_Szerk)
        x.centralwidget.setObjectName("centralwidget")
        x.frame = QtWidgets.QFrame(x.centralwidget)
        x.frame.setGeometry(QtCore.QRect(10, 10, 631, 621))
        font = QtGui.QFont()
        font.setPointSize(11)
        x.frame.setFont(font)
        x.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        x.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        x.frame.setObjectName("frame")
        x.pushButton_mentes = QtWidgets.QPushButton(x.frame)
        x.pushButton_mentes.setGeometry(QtCore.QRect(230, 560, 91, 41))
        x.pushButton_mentes.setObjectName("pushButton_mentes")
        x.pushButton_megse = QtWidgets.QPushButton(x.frame)
        x.pushButton_megse.setGeometry(QtCore.QRect(340, 560, 91, 41))
        x.pushButton_megse.setDefault(True)
        x.pushButton_megse.clicked.connect(lambda: Ui_Mezok_Szerk.close())
        x.pushButton_megse.setObjectName("pushButton_megse")
        x.label = QtWidgets.QLabel(x.frame)
        x.label.setGeometry(QtCore.QRect(30, 10, 141, 21))
        x.label.setObjectName("label")
        x.label_2 = QtWidgets.QLabel(x.frame)
        x.label_2.setGeometry(QtCore.QRect(20, 270, 201, 21))
        x.label_2.setObjectName("label_2")
        x.tableWidget_mutato = QtWidgets.QTableWidget(x.frame)
        x.tableWidget_mutato.setGeometry(QtCore.QRect(30, 40, 581, 211))
        x.tableWidget_mutato.setRowCount(4)
        x.tableWidget_mutato.setObjectName("tableWidget_mutato")
        x.tableWidget_mutato.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_mutato.setItem(3, 2, item)
        x.tableWidget_mutato.horizontalHeader().setSortIndicatorShown(False)
        x.tableWidget_mutato.horizontalHeader().setStretchLastSection(True)
        x.tableWidget_mutato.verticalHeader().setStretchLastSection(False)
        x.tableWidget_nomen = QtWidgets.QTableWidget(x.frame)
        x.tableWidget_nomen.setGeometry(QtCore.QRect(30, 300, 461, 221))
        x.tableWidget_nomen.setRowCount(4)
        x.tableWidget_nomen.setObjectName("tableWidget_nomen")
        x.tableWidget_nomen.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        x.tableWidget_nomen.setItem(3, 2, item)
        x.tableWidget_nomen.horizontalHeader().setSortIndicatorShown(False)
        x.tableWidget_nomen.horizontalHeader().setStretchLastSection(True)
        x.tableWidget_nomen.verticalHeader().setStretchLastSection(False)
        x.checkBox = QtWidgets.QCheckBox(x.frame)
        x.checkBox.setGeometry(QtCore.QRect(520, 80, 21, 21))
        x.checkBox.setText("")
        x.checkBox.setObjectName("checkBox")
        x.checkBox_2 = QtWidgets.QCheckBox(x.frame)
        x.checkBox_2.setGeometry(QtCore.QRect(520, 110, 21, 21))
        x.checkBox_2.setText("")
        x.checkBox_2.setObjectName("checkBox_2")
        x.checkBox_3 = QtWidgets.QCheckBox(x.frame)
        x.checkBox_3.setGeometry(QtCore.QRect(520, 140, 21, 21))
        x.checkBox_3.setText("")
        x.checkBox_3.setObjectName("checkBox_3")
        x.checkBox_4 = QtWidgets.QCheckBox(x.frame)
        x.checkBox_4.setGeometry(QtCore.QRect(520, 170, 21, 21))
        x.checkBox_4.setText("")
        x.checkBox_4.setObjectName("checkBox_4")
        x.checkBox_5 = QtWidgets.QCheckBox(x.frame)
        x.checkBox_5.setGeometry(QtCore.QRect(410, 340, 21, 21))
        x.checkBox_5.setText("")
        x.checkBox_5.setObjectName("checkBox_5")
        x.checkBox_6 = QtWidgets.QCheckBox(x.frame)
        x.checkBox_6.setGeometry(QtCore.QRect(410, 370, 21, 21))
        x.checkBox_6.setText("")
        x.checkBox_6.setObjectName("checkBox_6")
        x.checkBox_7 = QtWidgets.QCheckBox(x.frame)
        x.checkBox_7.setGeometry(QtCore.QRect(410, 400, 21, 21))
        x.checkBox_7.setText("")
        x.checkBox_7.setObjectName("checkBox_7")
        x.checkBox_8 = QtWidgets.QCheckBox(x.frame)
        x.checkBox_8.setGeometry(QtCore.QRect(410, 430, 21, 21))
        x.checkBox_8.setText("")
        x.checkBox_8.setObjectName("checkBox_8")
        Ui_Mezok_Szerk.setCentralWidget(x.centralwidget)
        x.menubar = QtWidgets.QMenuBar(Ui_Mezok_Szerk)
        x.menubar.setGeometry(QtCore.QRect(0, 0, 665, 21))
        x.menubar.setObjectName("menubar")
        Ui_Mezok_Szerk.setMenuBar(x.menubar)
        x.statusbar = QtWidgets.QStatusBar(Ui_Mezok_Szerk)
        x.statusbar.setObjectName("statusbar")
        Ui_Mezok_Szerk.setStatusBar(x.statusbar)

        x.retranslateUi(Ui_Mezok_Szerk)
        QtCore.QMetaObject.connectSlotsByName(Ui_Mezok_Szerk)

    def retranslateUi(x, Ui_Mezok_Szerk):
        _translate = QtCore.QCoreApplication.translate
        Ui_Mezok_Szerk.setWindowTitle(_translate("Ui_Mezok_Szerk", "Kiválasztott rekord mezőinek a kezelése"))
        x.pushButton_mentes.setText(_translate("Ui_Mezok_Szerk", "Mentés"))
        x.pushButton_megse.setText(_translate("Ui_Mezok_Szerk", "Mégse"))
        x.label.setText(_translate("Ui_Mezok_Szerk", "Mutatók kiválasztása:"))
        x.label_2.setText(_translate("Ui_Mezok_Szerk", "Nómenklatúrák kiválasztása:"))
        item = x.tableWidget_mutato.horizontalHeaderItem(0)
        item.setText(_translate("Ui_Mezok_Szerk", "Változó neve"))
        item = x.tableWidget_mutato.horizontalHeaderItem(1)
        item.setText(_translate("Ui_Mezok_Szerk", "Hossz"))
        item = x.tableWidget_mutato.horizontalHeaderItem(2)
        item.setText(_translate("Ui_Mezok_Szerk", "Típus"))
        item = x.tableWidget_mutato.horizontalHeaderItem(3)
        item.setText(_translate("Ui_Mezok_Szerk", "Mutató csoport"))
        item = x.tableWidget_mutato.horizontalHeaderItem(4)
        item.setText(_translate("Ui_Mezok_Szerk", "Rekordhoz ad"))
        __sortingEnabled = x.tableWidget_mutato.isSortingEnabled()
        x.tableWidget_mutato.setSortingEnabled(False)
        item = x.tableWidget_mutato.item(0, 0)
        item.setText(_translate("Ui_Mezok_Szerk", "Testsuly"))
        item = x.tableWidget_mutato.item(0, 1)
        item.setText(_translate("Ui_Mezok_Szerk", "3"))
        item = x.tableWidget_mutato.item(0, 2)
        item.setText(_translate("Ui_Mezok_Szerk", "Egész szám"))
        item = x.tableWidget_mutato.item(1, 0)
        item.setText(_translate("Ui_Mezok_Szerk", "Datum"))
        item = x.tableWidget_mutato.item(1, 1)
        item.setText(_translate("Ui_Mezok_Szerk", "8"))
        item = x.tableWidget_mutato.item(1, 2)
        item.setText(_translate("Ui_Mezok_Szerk", "Dátum"))
        item = x.tableWidget_mutato.item(2, 0)
        item.setText(_translate("Ui_Mezok_Szerk", "sum_bevetel"))
        item = x.tableWidget_mutato.item(2, 1)
        item.setText(_translate("Ui_Mezok_Szerk", "15"))
        item = x.tableWidget_mutato.item(2, 2)
        item.setText(_translate("Ui_Mezok_Szerk", "Egész szám"))
        item = x.tableWidget_mutato.item(3, 0)
        item.setText(_translate("Ui_Mezok_Szerk", "Adokedvezmeny"))
        item = x.tableWidget_mutato.item(3, 1)
        item.setText(_translate("Ui_Mezok_Szerk", "8"))
        item = x.tableWidget_mutato.item(3, 2)
        item.setText(_translate("Ui_Mezok_Szerk", "Lebegőpontos szám"))
        x.tableWidget_mutato.setSortingEnabled(__sortingEnabled)
        item = x.tableWidget_nomen.horizontalHeaderItem(0)
        item.setText(_translate("Ui_Mezok_Szerk", "Változó neve"))
        item = x.tableWidget_nomen.horizontalHeaderItem(1)
        item.setText(_translate("Ui_Mezok_Szerk", "Hossz"))
        item = x.tableWidget_nomen.horizontalHeaderItem(2)
        item.setText(_translate("Ui_Mezok_Szerk", "Típus"))
        item = x.tableWidget_nomen.horizontalHeaderItem(3)
        item.setText(_translate("Ui_Mezok_Szerk", "Rekordhoz ad"))
        __sortingEnabled = x.tableWidget_nomen.isSortingEnabled()
        x.tableWidget_nomen.setSortingEnabled(False)
        item = x.tableWidget_nomen.item(0, 0)
        item.setText(_translate("Ui_Mezok_Szerk", "phone"))
        item = x.tableWidget_nomen.item(0, 1)
        item.setText(_translate("Ui_Mezok_Szerk", "1"))
        item = x.tableWidget_nomen.item(0, 2)
        item.setText(_translate("Ui_Mezok_Szerk", "Karakteres"))
        item = x.tableWidget_nomen.item(1, 0)
        item.setText(_translate("Ui_Mezok_Szerk", "address"))
        item = x.tableWidget_nomen.item(1, 1)
        item.setText(_translate("Ui_Mezok_Szerk", "18"))
        item = x.tableWidget_nomen.item(1, 2)
        item.setText(_translate("Ui_Mezok_Szerk", "Karakteres"))
        item = x.tableWidget_nomen.item(2, 0)
        item.setText(_translate("Ui_Mezok_Szerk", "telepules_id"))
        item = x.tableWidget_nomen.item(2, 1)
        item.setText(_translate("Ui_Mezok_Szerk", "9"))
        item = x.tableWidget_nomen.item(2, 2)
        item.setText(_translate("Ui_Mezok_Szerk", "Egész szám"))
        item = x.tableWidget_nomen.item(3, 0)
        item.setText(_translate("Ui_Mezok_Szerk", "postcode"))
        item = x.tableWidget_nomen.item(3, 1)
        item.setText(_translate("Ui_Mezok_Szerk", "8"))
        item = x.tableWidget_nomen.item(3, 2)
        item.setText(_translate("Ui_Mezok_Szerk", "Egész szám"))
        x.tableWidget_nomen.setSortingEnabled(__sortingEnabled)


